root: true
extends:
  - 'plugin:prettier/recommended'
  - '@nuxt/eslint-config'
  - '@vue/eslint-config-prettier'
rules:
  'vue/attribute-hyphenation': ['error', 'never']
  'vue/v-on-event-hyphenation': ['error', 'never']
